### ISSUE TITLE
Deprecation warning for urllib3 Retry method_whitelist parameter

### ISSUE THREAD

**Issue by bchopson** [cronitorio/cronitor-python#20]
urllib3 has deprecated the `method_whitelist` parameter of `Retry` in favor of `allowed_methods`

See urllib3/urllib3#2000

Also, urllib3 is missing from `install_requires`.

**Comment by danielnieto** [comment]
thanks for the update! When is the next release live?

**Comment by aflanagan** [comment]
Sorry for the slow reply - it's now been released! https://pypi.org/project/cronitor/
