### ISSUE TITLE
validate_config and apply_config timeout

### ISSUE THREAD

**Issue by yjszk** [cronitorio/cronitor-python#27]
If the number of monitors exceeds 150, the following error occurs in validate_config and apply_config.

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cronitor.io', port=443): Max retries exceeded with url: /api/monitors.yaml (Caused by ReadTimeoutError("HTTPSConnectionPool(host='cronitor.io', port=443): Read timed out. (read timeout=10)"))
```

I have proposed a revision in the following PR. Thank you for your consideration.
https://github.com/cronitorio/cronitor-python/pull/26

**Comment by aflanagan** [comment]
This is now available in the 4.7.0 release - https://pypi.org/project/cronitor/4.7.0/

Thanks for your help!
