### ISSUE TITLE
Standardizing Cronitor Clients

### ISSUE THREAD

**Issue by cronitorio** [cronitorio/cronitor-python#5]
Hi vy-labs team,

I hope you're all well! 

We'd like to start taking responsibility for providing Cronitor supported open-source client libraries. Our Github account would host the clients and take a more active roll in the development of all clients. We'd like to start with Ruby, Python, Java, PHP, Elixir, Javascript, and Bash - https://cronitor.io/docs/open-source-libraries - as well as open-source our own Go client.

Our goal is to help standardize documentation, nomenclature, feature development, and testing, as well as keeping the APIs current, and, in some cases, adding or consolidating Ping and Monitor APIs.

Ideally, we'd like to transfer ownership of existing libraries for continuity. We'll clearly note original client authors on the README. And any maintainers who would like to continue contributing to the projects will continue to have maintainer access. Would you be interested in helping us do this for the Python library?

**Comment by aflanagan** [comment]
Hi there,

I wanted to reach out one more about our interest in maintaining the cronitor python library and continuing to publish updates to pypi. Please let us know if you would allow us to become the maintainers of this library as well as the corresponding pypi account.

Thanks!

**Comment by xrage** [comment]
@aflanagan Sure. It would be great if you are interested in maintaining this. Please share your PyPI details so we can add you as an owner of this package.

**Comment by aflanagan** [comment]
hi @xrage thanks so much! Our pypi username is `cronitor`. If you would like to transfer this repository to our github organization I can add you as a maintainer there.

**Comment by xrage** [comment]
- Yes, We can transfer this repo to your org.
- PyPI :  Users email must be verified to get ownership of a PyPi project. Please fix this for `cronitor`.

**Comment by xrage** [comment]
@aflanagan to transfer this first we need to delete forked repo i.e. https://github.com/cronitorio/cronitor-python

**Comment by aflanagan** [comment]
Thank you @xrage! I have deleted the fork and verified the primary email address on PyPI .

**Comment by xrage** [comment]
Great, Migrated. You can rename it now.

**Comment by xrage** [comment]
Added `cronitor` as package owner on PyPI.

**Comment by aflanagan** [comment]
Thanks!
